### PR TITLE
Common Lisp bot

### PR DESCRIPTION
**Pull request by HenryS1**
Common Lisp sample bot using the SBCL Lisp compiler.

### CODE REVIEW

**Comment by HenryS1** [comment]
Has anyone taken a look at this yet?

**Comment by Blaarkies** [comment]
We will have a deeper look through the code when possible

**Comment by HenryS1** [comment]
Great thanks :)

**Comment by HenryS1** [comment]
Has anyone managed to take a look yet?

**Comment by Blaarkies** [comment]
Hi @HenryS1 

I am working through the readme, but can't get this to compile. I am getting this error:
```
debugger invoked on a SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread
#<THREAD "main thread" RUNNING {23D30061}>:
  The name "ASDF" does not designate any package.
```

I am not experienced in LISP at all, do you mind helping someone new to the language? 😄

**Comment by HenryS1** [comment]
I fixed an exception that was being swallowed in the game runner and causing the command.txt not to be written. It worked on the example-state.json, but I hadn't tried it in the runner until yesterday. Could you put build and run instructions for the runner somewhere? It was a little tedious setting it up and I think it would improve the process for others. Thanks @Blaarkies @FoamyZA.

**Comment by HenryS1** [comment]
Please merge this if you're happy with it.

**Comment by Blaarkies** [comment]
Hi @HenryS1 

The changes we made with the v1.1.2 release seem to break the LISP bot. Would you please help by submitting an update to the starter bot?

**Comment by HenryS1** [comment]
I’m going overseas tonight for a week. I’ll fix it when I get back.

**Comment by HenryS1** [comment]
@Blaarkies, I compiled v1.1.2 and ran the GameRunner. It's not giving any trouble for me. What's going wrong for you?

**Comment by HenryS1** [comment]
@Blaarkies please let me know what problem you're having with the bot so that I can try and fix it. Thanks

**Comment by Blaarkies** [comment]
I was mistaken. Testing it now and it works as expected, sorry for the confusion 😄

**Comment by HenryS1** [comment]
No problem :)

**Pull request merged**
